In [2]:
import numpy as np


In [6]:
arr=np.array(1,'int')
arr


array(1)

In [7]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [10]:
arr2=np.array(["apple","mango","banana","orange"])
arr2

array(['apple', 'mango', 'banana', 'orange'], dtype='<U6')

In [11]:
arr3=np.array([1,2,"hello"])
arr3

array(['1', '2', 'hello'], dtype='<U21')

In [12]:
#2d array Rows and columns

arr4=np.array([[1,2],[3,4]])
arr4

array([[1, 2],
       [3, 4]])

In [18]:
#3d array
arr5 = np.array([
    
        [[5,6],[7,8]],
        [[1,2],[4,6]]
    
])
print(arr5)
print(arr5.shape)

[[[5 6]
  [7 8]]

 [[1 2]
  [4 6]]]
(2, 2, 2)


In [20]:
#special creation function for array

np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [29]:
#identity matrix

identity_matrix=np.eye(1)
print(identity_matrix.shape)
print(identity_matrix)

(1, 1)
[[1.]]


In [30]:
ar=np.array([[1,2,3],[5,6,7],[9,10,11]])
ar[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [31]:
ar[:,1:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [32]:
ar[:,:-1]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [34]:
ar[1][1]=200
ar

array([[  1,   2,   3],
       [  5, 200,   7],
       [  9,  10,  11]])

In [44]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,4])

print(a+b)
print(a-b)
print(a*b)
print(a/b)


[5 7 9 8]
[-3 -3 -3  0]
[ 4 10 18 16]
[0.25 0.4  0.5  1.  ]


In [45]:
np.sum(a)
print(np.sum(a))

10


In [46]:
np.sum(b)
print(np.sum(b))

19


In [47]:
np.mean(a)

np.float64(2.5)

In [48]:
np.median(a)

np.float64(2.5)

In [49]:
np.std(a)

np.float64(1.118033988749895)

In [50]:
np.min(a)

np.int64(1)

In [51]:
np.max(a)

np.int64(4)

In [52]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [53]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [55]:
#reshaping

ar1=np.array([1,2,3,4,5,6])


In [57]:
ar1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
a1=np.array([1,2])
a2=np.array([3,4])
np.concatenate((a1,a2))

array([1, 2, 3, 4])

In [62]:
#treasure hunt game
arr=np.zeros((3,3),dtype=int)
r=np.random.randint(0,3)
c=np.random.randint(0,3)
arr[r,c]=9
row=int(input("enter row: "))
column=int(input("enter column: "))
if arr[row,column]==9:
    print("you won")
else:
    print("try again")
print(arr)




try again
[[0 0 0]
 [0 0 0]
 [0 0 9]]
